---
language: python
python:
  - "2.7"
  - "3.3"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - py.test agavepy/tests/test_agave_basic.py
  - make docs
before_install:
  - pip install sphinx>=1.6.3
